/**:
  ros__parameters:
    port: "/dev/ttyUSB1"
    baud: 115200

    frame_id: "gps_link"
    velocity_frame_id: "enu"

    raw_topic: "/inspva/raw"
    navsat_topic: "/fix"
    velocity_topic: "/inspva/velocity"

    publish_raw: true
    publish_navsat: true
    publish_velocity: true

    publish_rate: 200.0
    debug: true